STATIC_CATEGORY_MAPPING = {
    'packaged food > ready to cook': {'category_id': 1, 'category_name': 'Ready To Cook', 'slug': 'ready-to-cook-aesc-readytocook', 'parent_id': 32, 'category_level': 2},
    'dairy & beverages > beverages': {'category_id': 2, 'category_name': 'Beverages', 'slug': 'beverages-aesc-beverages', 'parent_id': 31, 'category_level': 2},
    'packaged food > biscuits & cookies': {'category_id': 3, 'category_name': 'Biscuits & Cookies', 'slug': 'biscuits---cookies-aesc-biscuitsandcookies', 'parent_id': 32, 'category_level': 2},
    'personal care & beauty > bath & body': {'category_id': 4, 'category_name': 'Bath & Body', 'slug': 'bath-body', 'parent_id': 36, 'category_level': 2},
    'home & kitchen > detergent & fabric care': {'category_id': 5, 'category_name': 'Detergent & Fabric Care', 'slug': 'detergent---fabric-care-aesc-detergentsandfabriccare', 'parent_id': 34, 'category_level': 2},
    'home & kitchen > cleaners': {'category_id': 6, 'category_name': 'Cleaners', 'slug': 'cleaners-aesc-cleaners', 'parent_id': 34, 'category_level': 2},
    'dairy & beverages > dairy > milk': {'category_id': 7, 'category_name': 'Milk', 'slug': 'milk-aesc-milksc2', 'parent_id': 55, 'category_level': 3},
    'dairy & beverages > dairy > cheese': {'category_id': 8, 'category_name': 'Cheese', 'slug': 'cheese-aesc-cheesesc2', 'parent_id': 55, 'category_level': 3},
    'packaged food > ketchup & sauce': {'category_id': 9, 'category_name': 'Ketchup & Sauce', 'slug': 'ketchup---sauce-aesc-ketchupandsauces', 'parent_id': 32, 'category_level': 2},
    'packaged food > pickles': {'category_id': 10, 'category_name': 'Pickles', 'slug': 'pickles-aesc-pickles', 'parent_id': 32, 'category_level': 2},
    'grocery > dmart grocery > atta': {'category_id': 11, 'category_name': 'Atta', 'slug': 'atta-aesc-attasc2', 'parent_id': 94, 'category_level': 3},
    'packaged food > chips & wafers': {'category_id': 12, 'category_name': 'Chips & Wafers', 'slug': 'chips---wafers-aesc-chips---waferssc2', 'parent_id': 32, 'category_level': 2},
    'packaged food > oats': {'category_id': 13, 'category_name': 'Oats', 'slug': 'oats-aesc-oatssc2', 'parent_id': 32, 'category_level': 2},
    'dairy & beverages > beverages > green tea': {'category_id': 14, 'category_name': 'Green Tea', 'slug': 'green-tea-aesc-green-teasc2', 'parent_id': 2, 'category_level': 3},
    'dairy & beverages > beverages > cold drinks': {'category_id': 15, 'category_name': 'Cold Drinks', 'slug': 'soft-drinks-aesc-soft-drinkssc2', 'parent_id': 2, 'category_level': 3},
    'personal care & beauty > skin care': {'category_id': 16, 'category_name': 'Skin Care', 'slug': 'skin-care-208510--1', 'parent_id': 36, 'category_level': 2},
    'personal care & beauty > skin care > body lotions': {'category_id': 17, 'category_name': 'Body Lotions', 'slug': 'body-lotions-scrubs', 'parent_id': 16, 'category_level': 3},
    'personal care & beauty > skin care > baby powder': {'category_id': 18, 'category_name': 'Baby Powder', 'slug': 'baby-powder-aesc-baby-powdersc2', 'parent_id': 16, 'category_level': 3},
    'personal care & beauty > bath & body > bath soaps': {'category_id': 19, 'category_name': 'Bath Soaps', 'slug': 'soaps-aesc-soapssc2', 'parent_id': 4, 'category_level': 3},
    'personal care & beauty > bath & body > hair shampoos': {'category_id': 20, 'category_name': 'Hair Shampoos', 'slug': 'hair-shampoos-aesc-hair-shampoossc2', 'parent_id': 4, 'category_level': 3},
    'personal care & beauty > toothpaste': {'category_id': 21, 'category_name': 'Toothpaste', 'slug': 'toothpaste-aesc-toothpastesc2', 'parent_id': 36, 'category_level': 2},
    'baby & kids > diapering > diapers': {'category_id': 22, 'category_name': 'Diapers', 'slug': 'diapers-aesc-diaperssc2', 'parent_id': 90, 'category_level': 3},
    'home & kitchen > crockery set': {'category_id': 23, 'category_name': 'Crockery Set', 'slug': 'crockery-sets-aesc-crockery-sets-sc2', 'parent_id': 34, 'category_level': 2},
    'home & kitchen > cookware > tawas & sauce pans': {'category_id': 24, 'category_name': 'Tawas & Sauce Pans', 'slug': 'tawas-sauce-pans', 'parent_id': 60, 'category_level': 3},
    'home utility & organisers > jar container': {'category_id': 25, 'category_name': 'Jar Container', 'slug': 'jars---containers', 'parent_id': 41, 'category_level': 2},
    'bags & more > trolley bags': {'category_id': 26, 'category_name': 'Trolley bags', 'slug': 'trolley-bags-201503--1', 'parent_id': 44, 'category_level': 2},
    'home & kitchen > cleaners > bathroom cleaners': {'category_id': 27, 'category_name': 'Bathroom Cleaners', 'slug': 'bathroom-cleaners', 'parent_id': 6, 'category_level': 3},
    'home & kitchen > detergent & fabric care > detergent powder': {'category_id': 28, 'category_name': 'Detergent Powder', 'slug': 'detergent-powder-aesc-detergent-powder-sc2', 'parent_id': 5, 'category_level': 3},
    'home & kitchen > detergent & fabric care > dishwash liquids': {'category_id': 29, 'category_name': 'Dishwash Liquids', 'slug': 'dishwash-liquids--1', 'parent_id': 5, 'category_level': 3},
    'stationery > stationery kits': {'category_id': 30, 'category_name': 'Stationery Kits', 'slug': 'stationery-kits', 'parent_id': 40, 'category_level': 2},
    'dairy & beverages': {'category_id': 31, 'category_name': 'Dairy & Beverages', 'slug': 'dairy---beverages-aesc-dairyandbeveragescore', 'parent_id': None, 'category_level': 1},
    'packaged food': {'category_id': 32, 'category_name': 'Packaged Food', 'slug': 'packaged-food-aesc-packagedfoodcore', 'parent_id': None, 'category_level': 1},
    'fruits & vegetables': {'category_id': 33, 'category_name': 'Fruits & Vegetables', 'slug': 'fruits---vegetables-aesc-fruitsandvegetablescore', 'parent_id': None, 'category_level': 1},
    'home & kitchen': {'category_id': 34, 'category_name': 'Home & Kitchen', 'slug': 'home---kitchen-aesc-homeandkitchencore', 'parent_id': None, 'category_level': 1},
    'kitchen & dining': {'category_id': 35, 'category_name': 'Kitchen & Dining', 'slug': 'kitchen-dining', 'parent_id': None, 'category_level': 1},
    'personal care & beauty': {'category_id': 36, 'category_name': 'Personal Care & Beauty', 'slug': 'personal-care-beauty', 'parent_id': None, 'category_level': 1},
    'sports & fitness': {'category_id': 37, 'category_name': 'Sports & Fitness', 'slug': 'sports-and-fitness', 'parent_id': None, 'category_level': 1},
    'baby & kids > baby care': {'category_id': 38, 'category_name': 'Baby Care', 'slug': 'baby-care', 'parent_id': 89, 'category_level': 2},
    'books': {'category_id': 39, 'category_name': 'Books', 'slug': 'books-204003--1', 'parent_id': None, 'category_level': 1},
    'stationery': {'category_id': 40, 'category_name': 'Stationery', 'slug': 'school-supplies', 'parent_id': None, 'category_level': 1},
    'home utility & organisers': {'category_id': 41, 'category_name': 'Home Utility & Organisers', 'slug': 'home-utility-organisers', 'parent_id': None, 'category_level': 1},
    'electronics & appliances': {'category_id': 42, 'category_name': 'Electronics & Appliances', 'slug': 'electronics-appliances', 'parent_id': None, 'category_level': 1},
    'footwear': {'category_id': 43, 'category_name': 'Footwear', 'slug': 'aesc--footwear', 'parent_id': None, 'category_level': 1},
    'bags & more': {'category_id': 44, 'category_name': 'Bags & More', 'slug': 'trolley-bags-handbags-more', 'parent_id': None, 'category_level': 1},
    'gifting': {'category_id': 45, 'category_name': 'Gifting', 'slug': 'gifting-229002--1', 'parent_id': None, 'category_level': 1},
    'seasonal & more': {'category_id': 46, 'category_name': 'Seasonal & More', 'slug': 'specials-seasonal', 'parent_id': None, 'category_level': 1},
    'grocery > dmart grocery > dals': {'category_id': 47, 'category_name': 'Dals', 'slug': 'dals-aesc-dals', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > pulses': {'category_id': 48, 'category_name': 'Pulses', 'slug': 'pulses-aesc-pulses3', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > dry fruits': {'category_id': 49, 'category_name': 'Dry Fruits', 'slug': 'dry-fruits-aesc-dryfruits2', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > cooking oil': {'category_id': 50, 'category_name': 'Cooking Oil', 'slug': 'cooking-oil-aesc-cookingoil', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > ghee & vanaspati': {'category_id': 51, 'category_name': 'Ghee & Vanaspati', 'slug': 'ghee---vanaspati-aesc-gheeandvanaspati', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > flours & grains': {'category_id': 52, 'category_name': 'Flours & Grains', 'slug': 'flours---grains-aesc-floursandgrains4', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > rice & rice products': {'category_id': 53, 'category_name': 'Rice & Rice Products', 'slug': 'rice---rice-products-aesc-riceandriceproducts4', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > salt / sugar / jaggery': {'category_id': 54, 'category_name': 'Salt / Sugar / Jaggery', 'slug': 'salt---sugar---jaggery-aesc-saltsugarjaggery4', 'parent_id': 94, 'category_level': 3},
    'dairy & beverages > dairy': {'category_id': 55, 'category_name': 'Dairy', 'slug': 'dairy-aesc-dairy', 'parent_id': 31, 'category_level': 2},
    'fruits & vegetables > fresh fruits': {'category_id': 56, 'category_name': 'Fresh Fruits', 'slug': 'fresh-fruits-aesc-freshfruits', 'parent_id': 33, 'category_level': 2},
    'fruits & vegetables > vegetables': {'category_id': 57, 'category_name': 'Vegetables', 'slug': 'vegetables-aesc-vegetables', 'parent_id': 33, 'category_level': 2},
    'home & kitchen > cleaners > utensil cleaners': {'category_id': 58, 'category_name': 'Utensil Cleaners', 'slug': 'utensil-cleaners-aesc-utensilcleaners', 'parent_id': 6, 'category_level': 3},
    'furniture & decor': {'category_id': 59, 'category_name': 'Furniture & Decor', 'slug': 'home-decor-216014--1', 'parent_id': None, 'category_level': 1},
    'home & kitchen > cookware': {'category_id': 60, 'category_name': 'Cookware', 'slug': 'cookware-218510--1', 'parent_id': 34, 'category_level': 2},
    'pooja needs': {'category_id': 61, 'category_name': 'Pooja Needs', 'slug': 'pooja-needs-aesc-poojaneeds', 'parent_id': None, 'category_level': 1},
    'home & kitchen > cookware > cookware set': {'category_id': 62, 'category_name': 'Cookware Set', 'slug': 'serveware-218514--1', 'parent_id': 60, 'category_level': 3},
    'home & kitchen > drinkware': {'category_id': 63, 'category_name': 'Drinkware', 'slug': 'drinkware', 'parent_id': 34, 'category_level': 2},
    'shop by room': {'category_id': 64, 'category_name': 'Shop By Room', 'slug': 'shop-by-room', 'parent_id': None, 'category_level': 1},
    'packaged food > snacks & farsans': {'category_id': 65, 'category_name': 'Snacks & Farsans', 'slug': 'snacks---farsans-aesc-snacksandfarsans', 'parent_id': 32, 'category_level': 2},
    'packaged food > breakfast cereals': {'category_id': 66, 'category_name': 'Breakfast Cereals', 'slug': 'breakfast-cereals-aesc-breakfastcereals', 'parent_id': 32, 'category_level': 2},
    'packaged food > chocolates & candies': {'category_id': 67, 'category_name': 'Chocolates & Candies', 'slug': 'chocolates---candies', 'parent_id': 32, 'category_level': 2},
    'packaged food > pasta & noodles': {'category_id': 68, 'category_name': 'Pasta & Noodles', 'slug': 'pasta---noodles-aesc-pastaandnoodles', 'parent_id': 32, 'category_level': 2},
    'packaged food > heathy food': {'category_id': 69, 'category_name': 'Heathy Food', 'slug': 'health-food-aesc-healthfood', 'parent_id': 32, 'category_level': 2},
    'packaged food > bakery': {'category_id': 70, 'category_name': 'Bakery', 'slug': 'bakery-aesc-bakery', 'parent_id': 32, 'category_level': 2},
    'packaged food > frozen food': {'category_id': 71, 'category_name': 'Frozen Food', 'slug': 'frozen-foods-aesc-frozenfoods', 'parent_id': 32, 'category_level': 2},
    'packaged food > sweets': {'category_id': 72, 'category_name': 'Sweets', 'slug': 'sweets-aesc-sweets', 'parent_id': 32, 'category_level': 2},
    'festive specials': {'category_id': 73, 'category_name': 'Festive Specials', 'slug': 'festive-specials', 'parent_id': None, 'category_level': 1},
    'bed & bath': {'category_id': 74, 'category_name': 'Bed & Bath', 'slug': 'home-furnishing-decor', 'parent_id': None, 'category_level': 1},
    'bed & bath > bedding': {'category_id': 75, 'category_name': 'Bedding', 'slug': 'bedsheets-more', 'parent_id': 74, 'category_level': 2},
    'bed & bath > curtains': {'category_id': 76, 'category_name': 'Curtains', 'slug': 'curtains-216012--1', 'parent_id': 74, 'category_level': 2},
    'bed & bath > bedroom storage': {'category_id': 78, 'category_name': 'Bedroom Storage', 'slug': 'storage-organizers', 'parent_id': 74, 'category_level': 2},
    'bed & bath > bath accessories': {'category_id': 79, 'category_name': 'Bath Accessories', 'slug': 'bath-range', 'parent_id': 74, 'category_level': 2},
    'electronics & accessories': {'category_id': 80, 'category_name': 'Electronics & Accessories', 'slug': 'computer-mobile-accessories', 'parent_id': None, 'category_level': 1},
    'home appliances': {'category_id': 81, 'category_name': 'Home Appliances', 'slug': 'home-appliances-216003--1', 'parent_id': None, 'category_level': 1},
    'home appliances > kitchen appliances': {'category_id': 82, 'category_name': 'Kitchen Appliances', 'slug': 'kitchen-appliances-216005--1', 'parent_id': 80, 'category_level': 2},
    'electronics & appliances > personal care appliances': {'category_id': 83, 'category_name': 'Personal Care Appliances', 'slug': 'personal-care-appliances-216007--1', 'parent_id': 42, 'category_level': 2},
    'clothing & accessories': {'category_id': 84, 'category_name': 'Clothing & Accessories', 'slug': 'clothing-accessories-aesc-clothingaccessories', 'parent_id': None, 'category_level': 1},
    'clothing & accessories > men clothing': {'category_id': 85, 'category_name': 'Men Clothing', 'slug': 'mens-mens', 'parent_id': 83, 'category_level': 2},
    'clothing & accessories > women clothing': {'category_id': 86, 'category_name': 'Women Clothing', 'slug': 'womens-womens', 'parent_id': 83, 'category_level': 2},
    'clothing & accessories > accessories': {'category_id': 87, 'category_name': 'Accessories', 'slug': 'accessories--1', 'parent_id': 83, 'category_level': 2},
    "footwear > men's footwear": {'category_id': 88, 'category_name': "Men's Footwear", 'slug': 'mens-footwear', 'parent_id': 43, 'category_level': 2},
    "footwear > women's footwear": {'category_id': 89, 'category_name': "Women's Footwear", 'slug': 'womens-footwear', 'parent_id': 43, 'category_level': 2},
    'baby & kids': {'category_id': 90, 'category_name': 'Baby & Kids', 'slug': 'baby---kids-aesc-babyandkidscore', 'parent_id': None, 'category_level': 1},
    'baby & kids > diapering': {'category_id': 91, 'category_name': 'Diapering', 'slug': 'diapers---wipes-aesc-diapersandwipes', 'parent_id': 89, 'category_level': 2},
    'baby & kids > baby food': {'category_id': 92, 'category_name': 'Baby Food', 'slug': 'baby-food-aesc-babyfood', 'parent_id': 89, 'category_level': 2},
    'baby & kids > baby gear & furniture': {'category_id': 93, 'category_name': 'Baby Gear & Furniture', 'slug': 'baby-gear---furniture', 'parent_id': 89, 'category_level': 2},
    'grocery': {'category_id': 94, 'category_name': 'Grocery', 'slug': 'grocery-aesc-grocerycore', 'parent_id': None, 'category_level': 1},
    'grocery > dmart grocery': {'category_id': 95, 'category_name': 'DMart Grocery', 'slug': 'dmart-grocery-aesc-grocerycore2', 'parent_id': 93, 'category_level': 2},
    'grocery > dmart grocery > grocery/dmart grocery/ dry fruits': {'category_id': 96, 'category_name': 'Grocery/DMart Grocery/ Dry Fruits', 'slug': None, 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > masala & spices': {'category_id': 97, 'category_name': 'Masala & Spices', 'slug': 'masala---spices-aesc-masalaandspices4', 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > masala & spices > chilli powder': {'category_id': 98, 'category_name': 'Chilli Powder', 'slug': None, 'parent_id': 96, 'category_level': 4},
    'grocery > dmart grocery > masala & spices > spices': {'category_id': 99, 'category_name': 'Spices', 'slug': None, 'parent_id': 96, 'category_level': 4},
    'grocery > dmart grocery > dals & pulses': {'category_id': 100, 'category_name': 'Dals & Pulses', 'slug': None, 'parent_id': 94, 'category_level': 3},
    'grocery > dmart grocery > grocery/dmart grocery/ flours & grains': {'category_id': 101, 'category_name': 'Grocery/DMart Grocery/ Flours & Grains', 'slug': None, 'parent_id': 94, 'category_level': 3},
}
